Zones peers
mapofzones/map-of-zones-web pull request #173
Opened 2022-07-26 23:47 UTC by ALashchotka

2022-07-28 12:12 UTC, sarious requested changes

2022-07-28 13:30 UTC, ALashchotka commented on src/components/ValueWithPending/ValueWithPending.props.ts
> +  value?: number | null;
Скорее всего да, когда добавлял отдельный компонент для PendingValue

2022-07-28 16:14 UTC, ALashchotka commented on src/components/Table/TableRowItem/TableRowItem.module.scss
> +  }
withBorder отличается для хедера и для тела таблицы
sticky пока идентичен, но сделан не финально, поэтому пока лежит так же отдельно для хедера и тела

2022-07-28 16:15 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.module.scss
> +    font-feature-settings: 'tnum' on, 'lnum' on;
Я бы временно оставил как есть, пока финально не разобрались с шрифтом, чтобы понять, насколько он будет влиять и на какие моменты

2022-07-28 16:16 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.module.scss
> +      &.navigationButtonActive {
Done

2022-07-28 16:16 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ShowMoreRow/ShowMoreRow.tsx
> +      ) : (
Done

2022-07-28 16:18 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.tsx
> +                variants={{ visible: { opacity: 0 }, hidden: { opacity: 1 } }}
Done

2022-07-28 16:18 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.tsx
> +      {channelsConfig.isChannelsVisible && (
Done

2022-07-28 16:20 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/useZoneDetails.ts
> +export function useZoneDetails(): { data: ZoneDetails | undefined; loading: boolean } {
Done

2022-07-28 16:24 UTC, ALashchotka commented on src/components/Table/TableHeaderItem/TableHeaderItem.module.scss
> +  top: -1px;
Done

2022-07-28 16:35 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ChannelRow/ChannelRow.module.scss
> +        background-color: #16161c;
Тут +- случайный цвет, которого нет в переменных. Могу внести как --black-450

2022-07-28 16:35 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ChannelRow/ChannelRow.tsx
> +          ) : (
Done

2022-07-28 16:47 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.tsx
> +              <div className={styles.logoContainer}>
Он нужен для границы вокруг логотипа. Т.к. размер лого устанавливается через параметры - дополнительный бордер ломает UI

2022-07-28 16:50 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ChannelRow/ChannelRow.tsx
> +          <div className={styles.position}>{index + 1}</div>
Реализовано идентично для всех видов строк таблицы, чтобы, при необходимости, легко можно было менять UI в одном классе, а не подбирать отдельно для каждого вида строк (строка с зоной, где стрелка; строка с каналами, где позиция; строка с Show More, где троеточие)

2022-07-28 16:50 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ShowMoreRow/ShowMoreRow.tsx
> +            <div className={styles.position}>...</div>
Реализовано идентично для всех видов строк таблицы, чтобы, при необходимости, легко можно было менять UI в одном классе, а не подбирать отдельно для каждого вида строк (строка с зоной, где стрелка; строка с каналами, где позиция; строка с Show More, где троеточие)

2022-07-28 17:41 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +        </div>
Done

2022-07-30 09:49 UTC, sarious commented on src/components/Table/TableRowItem/TableRowItem.module.scss
> +  }
понял, хорошо

2022-07-30 09:50 UTC, sarious commented on src/components/ValueWithPending/ValueWithPending.props.ts
> +  value?: number | null;
у тебя стоит расширение какое-то?

2022-07-30 09:50 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.module.scss
> +    font-feature-settings: 'tnum' on, 'lnum' on;
окей, пусть уже пока остается

2022-07-30 09:58 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ChannelRow/ChannelRow.module.scss
> +        background-color: #16161c;
это ты цвет такой сам придумал? потому что на дизайне не отмечено

2022-07-30 10:17 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePeers/ZonePeers.tsx
> +      </table>
?

2022-07-31 22:50 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/ChannelRow/ChannelRow.module.scss
> +        background-color: #16161c;
Он идёт белый с 3% прозрачностью. Но при прозрачном бэкграунде ломается UI. Поэтому взял такой же цвет, но без прозрачности. Вышел #16161c

2022-07-31 22:50 UTC, ALashchotka commented on src/components/ValueWithPending/ValueWithPending.props.ts
> +  value?: number | null;
Sort lines v1.9.1
https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines

2022-07-31 23:17 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableHeader/TableHeader.tsx
> +    </thead>
Done

2022-07-31 23:29 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/ZonePeers.tsx
> +      </table>
Done. Перенёс таблицу в компоненты

2022-07-31 23:33 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/ZonePeers.tsx
> +      </table>
Done. Перенёс в компоненты

2022-08-01 15:33 UTC, sarious commented on src/components/Table/Table.tsx
> +}: any) {
тип поставь. тут вроде не сложно

2022-08-01 15:35 UTC, sarious commented on src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.tsx
> +      <div className={styles.contentContainer}>
кажется, что div лишний. th уже есть контейнер

2022-08-01 17:01 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +}: any) {
Done

2022-08-01 17:38 UTC, ALashchotka commented on src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.tsx
> +      <div className={styles.contentContainer}>
Тут нужны доп. стили для контейнера, поэтому использовал th + div. Можешь попробовать в консоли перенести стили, UI поломается)

2022-08-02 21:18 UTC, closed without merging