zones_search: init search by zones at zones list zone page
mapofzones/map-of-zones-web pull request #175
Opened 2022-08-03 23:18 UTC by ALashchotka

2022-08-05 06:52 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +export function ZonesSearch({ currentZone, zonesList }: ZonesSearchProps): JSX.Element {
переименую, пожалуйста, это в ZonesSelector. или что-то похожее. первоочередная задача всё-таки выбора зоны а не поиска

2022-08-05 06:55 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +  );
обобщить не пробовал? точно такой же где-то код я реализовывал

2022-08-05 07:00 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +            </motion.div>
такую стрелку с анимацией ты уже реализовывал же. Обобщить в ArrowUpDown, AnimatedArrowUpDown или ArrowUpDownAnimated

2022-08-05 07:08 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZoneInfo/ZoneInfo.tsx
> +      })}
вынеси, пожалуйста, это в отдельный компонент. Не надо просто дублировать одну и ту же логику и компоненты.

2022-08-06 17:42 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +export function ZonesSearch({ currentZone, zonesList }: ZonesSearchProps): JSX.Element {
Done

2022-08-06 17:51 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +            </motion.div>
По сути да, но по реализации выйдет только:
_контейнер с классом, и внутри иконка_
т.к. все ключи для параметров анимации идут разные, а передавать их как пропсы выйдет как-то странно, как по мне.

2022-08-06 18:09 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +  );
Тоже не думаю, что стоит выносить простой фильтр по зонам в отдельный файл.
По сути, из общего, одна функция фильтра. В остальном слишком большая разница, имхо)

2022-08-06 18:46 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZoneInfo/ZoneInfo.tsx
> +      })}
Done

2022-08-08 07:11 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +  );
ну тут не просто фильтр. тут столько функций используется. потом надо будет например сделать, чтобы поиск был чувствительный к регистру, или не includes, а startWith использовать. забудешь потом, где у тебя такой же фильтр используется. или новый человек даже знать не будет. поправит в одном месте только

2022-08-08 07:13 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +            </motion.div>
а почему там ключи анимации разные? там же просто поворот на 180 градусов

2022-08-08 20:12 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonesSearch/ZonesSearch.tsx
> +  );
Done

2022-08-08 20:41 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +            </motion.div>
Done

2022-08-09 16:05 UTC, sarious requested changes

2022-08-09 16:05 UTC, sarious commented on src/pages/HomePage/Sidebar/ZonesInfo/ZonesInfoTable/ZonesInfoTable.tsx
>    );
так блин.. лучше же выделить  в кастомный хук useFilteredZones, например

2022-08-09 20:15 UTC, ALashchotka commented on src/pages/HomePage/Sidebar/ZonesInfo/ZonesInfoTable/ZonesInfoTable.tsx
>    );
Done

2022-08-10 06:38 UTC, sarious requested changes

2022-08-10 06:38 UTC, sarious commented on src/hooks/useFilteredZones.ts
> +}
так у тебя уже получился обычный метод. ты же убрал useMemo отсюда) верни, пожалуйста

2022-08-10 11:21 UTC, ALashchotka commented on src/hooks/useFilteredZones.ts
> +}
Done

2022-08-10 13:15 UTC, sarious approved these changes

2022-08-10 17:42 UTC, merged