Adaptive for Assets page and Zones page
mapofzones/map-of-zones-web pull request #176
Opened 2022-08-07 20:43 UTC by ALashchotka

2022-08-08 12:57 UTC, sarious requested changes

2022-08-08 12:59 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +              });
Только в одной таблице идёт первая колона sticky, в остальных по 2

2022-08-08 13:00 UTC, ALashchotka commented on src/index.scss
> +  > div {
Ругается линтер на #root

2022-08-08 13:03 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +  const { width: windowWidth } = useWindowSize();
UI достаточно сильно меняется при параметре isTableScrollable:
- меняются стили у таблицы
- добавляется граница к последнему isSticky столбцу строки тела таблицы
- меняются стили у столбцов isSticky для хедера и тела
возможно что-то ещё, пока первое, что вспомнил

2022-08-08 13:04 UTC, ALashchotka commented on src/hooks/useWindowSize.ts
> +export function useWindowSize() {
Тут проблема в шрифте, из-за того, что он моноширинный, все дизайнерские размеры и @media не подходят. Поэтому, на время, сделал таблицу прокручиваемой если размер таблицы больше чем экран, а не по @media, как в дизайне

2022-08-08 21:13 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +    <div className={cn(styles.container, { [styles.scrollable]: isTableScrollable }, className)}>
Done

2022-08-08 21:18 UTC, ALashchotka commented on src/components/TotalInfo/TotalInfo.module.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Done

2022-08-08 21:26 UTC, ALashchotka commented on src/components/TotalInfo/TotalInfo.module.scss
> +    > :nth-child(3) {
Done

2022-08-09 17:11 UTC, sarious commented on src/components/Table/Table.tsx
> +              });
ну это к тому, что можно <TableRowItem isSticky={true} для первой или первой-второй колонок выставить. разницы же нет, скролабл или не скролабл

2022-08-09 17:19 UTC, sarious commented on src/components/Table/Table.tsx
> +  const { width: windowWidth } = useWindowSize();
хм, ну ладно, мне кажется что можно как-то было дожать. ладно, потом сам посмотрю

2022-08-09 17:20 UTC, sarious commented on src/hooks/useWindowSize.ts
> +export function useWindowSize() {
если на время, то напиши todo

2022-08-09 20:26 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +              });
Получилось для isSticky стили поправить и сделать isSticky={true}.
Но всё равно нужен параметр для отображения границы у последнего isSticky столбца строки.

2022-08-09 20:26 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +  const { width: windowWidth } = useWindowSize();
Пробовал. Та же проблема и у https://coinmarketcap.com/

2022-08-09 20:30 UTC, ALashchotka commented on src/hooks/useWindowSize.ts
> +export function useWindowSize() {
Done

2022-08-10 06:42 UTC, sarious commented on src/components/Table/Table.tsx
> +  const { width: windowWidth } = useWindowSize();
ну ладно тогда

2022-08-10 06:45 UTC, sarious approved these changes

2022-08-10 11:19 UTC, merged