Analytics
mapofzones/map-of-zones-web pull request #179
Opened 2022-08-10 19:53 UTC by ALashchotka

2022-08-12 12:58 UTC, sarious requested changes

2022-08-12 12:58 UTC, sarious commented on src/hooks/useAnalytics.ts
> +const ZONES_PEERS_COLUMN_TITLE: Record<string, string> = {
когда выделишь в отдельную папку, то можно все эти константы и типы перенести в отдельный файл

2022-08-14 21:40 UTC, ALashchotka commented on src/hooks/useAnalytics.ts
> +  const getPageTitle = (pathname: string | null) => {
Done

2022-08-14 21:40 UTC, ALashchotka commented on src/hooks/useAnalytics.ts
> +  useEffect(() => {
Done

2022-08-14 21:40 UTC, ALashchotka commented on src/hooks/useAnalytics.ts
> +      trackEvent('sorted zone peers list', {
Done

2022-08-14 21:40 UTC, ALashchotka commented on src/hooks/useAnalytics.ts
> +const ZONES_PEERS_COLUMN_TITLE: Record<string, string> = {
Done

2022-08-14 21:42 UTC, ALashchotka commented on src/hooks/useAnalytics.ts
> +  const debouncedLocation = useDebounce(location, 500);
Т.к. в `location` приходит, к примеру:
```
/zone
/zone?period=24h
/zone?period=24h&columnKey=ibcVolume
```
получается, что будет 3 разные страницы, хотя пользователь сидел на одной

2022-08-16 11:20 UTC, sarious requested changes

2022-08-16 11:20 UTC, sarious commented on src/hooks/analytics/useAnalytics.ts
> +  useViewedZonesListPageAnalytics(currentPage, prevPage);
создай может хотя бы базовые папки в analytics: Home, Assests, Zones

2022-08-17 14:21 UTC, ALashchotka commented on src/hooks/analytics/useAnalytics.ts
> +  useSwitchedZoneSubtabAnalytics(currentPage, prevPage);
Done

2022-08-17 14:21 UTC, ALashchotka commented on src/hooks/analytics/useAnalytics.ts
> +  useViewedZonesListPageAnalytics(currentPage, prevPage);
Done

2022-08-18 13:27 UTC, sarious approved these changes

2022-08-19 09:07 UTC, merged