Mobile adaptive for zones and assets pages
mapofzones/map-of-zones-web pull request #183
Opened 2022-08-24 17:25 UTC by ALashchotka

2022-08-25 13:36 UTC, sarious requested changes

2022-08-25 13:36 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +  const isMobile = useMediaQuery('(max-width: 375px)');
всё как и выше

2022-08-25 13:36 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +        )}
а в отдельный компонент это выделить?

2022-08-25 13:36 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.module.scss
> +  }
дублирование стилей.  выделить это в какой-то BaseRow. не получится?

2022-08-25 13:36 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/TableRow/TableRow.module.scss
> +        left: 30px; // TODO: calculate dynamically
где-то уже видел.. вот придется потом во всех компонентах менять. где-то забудешь. попробуй как-то обобщить

2022-08-25 13:36 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.module.scss
> +          left: 30px; // TODO: calculate dynamically
то же самое.. видел уже этот код

2022-09-05 09:43 UTC, ALashchotka commented on src/hooks/useMediaQuery.ts
> +      matchMedia.addListener(handleChange);
Done

2022-09-05 09:43 UTC, ALashchotka commented on src/hooks/useMediaQuery.ts
> +        matchMedia.removeListener(handleChange);
Done

2022-09-05 09:43 UTC, ALashchotka commented on src/hooks/useMediaQuery.ts
> +  function handleChange() {
Done

2022-09-05 09:43 UTC, ALashchotka commented on src/hooks/useMediaQuery.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Done

2022-09-05 09:48 UTC, ALashchotka commented on src/components/PeriodSelector/PeriodSelector.tsx
> +          title: periodValue,
Done

2022-09-05 09:55 UTC, ALashchotka commented on src/components/Table/Table.tsx
> +  const isTableHorizontalScrollable = useMediaQuery('(max-width: 1440px)');
Можно сделать, но только если писать через :export модуль, по-другому никак не выходит

2022-09-05 10:02 UTC, ALashchotka commented on src/components/Table/TableRowItem/TableRowItem.module.scss
> +    &:first-child {
hover строки элемента должен торчать из таблицы на несколько пикселей

2022-09-05 10:03 UTC, ALashchotka commented on src/components/Table/TableHeader/TableHeaderItem/TableHeaderItem.module.scss
> +  th {
hover строки элемента должен торчать из таблицы на несколько пикселей

2022-09-05 10:04 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTable/TableRow/TableRow.tsx
> +  const isMobile = useMediaQuery('(max-width: 375px)');
Думаю, не нужно выделять под каждый размер отдельный хук, который будет отличаться только размером. Если он изменится - поискать по всему проекту использование одного хука не сильно будет затратным.

2022-09-05 10:04 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +  const isMobile = useMediaQuery('(max-width: 375px)');
Думаю, не нужно выделять под каждый размер отдельный хук, который будет отличаться только размером. Если он изменится - поискать по всему проекту использование одного хука не сильно будет затратным.

2022-09-05 10:05 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/TableRow/TableRow.module.scss
> +        left: 30px; // TODO: calculate dynamically
Для этого и стоит TODO, чтобы не потерять и не забыть)

2022-09-05 10:05 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.module.scss
> +          left: 30px; // TODO: calculate dynamically
Для этого и стоит TODO, чтобы не потерять и не забыть)

2022-09-05 10:09 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTable/TableRow/TableRow.module.scss
> +    }
Done

2022-09-05 10:10 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.module.scss
> +  }
А где тут дублирование стилей?

2022-09-05 10:22 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +        )}
Done

2022-09-05 11:08 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/TableRow/TableRow.module.scss
> +        left: 30px; // TODO: calculate dynamically
да я не только про эту строку, а про целый блок. у тебя есть TableRow, и ещё каких-то 2 Row с одинаковыми кажется стилями

2022-09-05 11:08 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.module.scss
> +  }
с другими компонентвами Row

2022-09-05 11:11 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.module.scss
> +  }
ChannelRow, ShowMoreRow.  можно же как-то стили в один компонент вынести. или хотя бы заимпортить повторяющиеся стили из одного файла
` import styles from './TableRow.module.scss';`

2022-09-05 11:37 UTC, sarious commented on src/pages/ZonesPage/ZonePage/ZonePage.tsx
> +  const isMobile = useMediaQuery('(max-width: 375px)');
ну ок, не критично пока

2022-09-05 11:38 UTC, sarious commented on src/pages/AssetsPage/AssetsTable/TableRow/TableRow.tsx
> +  const isMobile = useMediaQuery('(max-width: 375px)');
ладно, сам потом поменяю

2022-09-05 11:41 UTC, sarious commented on src/components/Table/TableRowItem/TableRowItem.module.scss
> +    &:first-child {
а, понял

2022-09-05 14:05 UTC, sarious requested changes

2022-09-10 14:58 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZoneNavigation/ZoneNavigation.tsx
> +export function ZoneNavigation({ data }: ZoneNavigationProps) {
Done

2022-09-10 15:00 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/TableRow/TableRow.module.scss
> +        left: 30px; // TODO: calculate dynamically
Там, по сути, стили относятся больше к контенту таблицы, чем к самой таблице. Есть совпадения, где контент совпадает (например номер строки), но он есть не во всех таблицах + UI слегка отличается

2022-09-10 15:16 UTC, ALashchotka commented on src/pages/ZonesPage/ZonePage/ZonePeers/TableRow/TableRow.module.scss
> +  }
Что смог то вынес

2022-09-11 15:10 UTC, sarious approved these changes

2022-09-12 09:26 UTC, merged