adaptive: add carousel for zones and assets total info
mapofzones/map-of-zones-web pull request #186
Opened 2022-09-16 20:35 UTC by ALashchotka

2022-09-17 08:27 UTC, sarious requested changes

2022-09-17 08:27 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +      {!isLaptopMedium && (
а почему ты не с помощью стилей блок скрывыешь? тут, кажется. спокойно можно сделать

2022-09-17 08:27 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTotalInfo/ZonesTotalInfo.tsx
> +      {!isLaptopMedium && (
лучше просто с помощью стилей

2022-09-17 10:06 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +      {!isLaptopMedium && (
Да, он стилями и был скрыт, но библиотека с каруселью смотрит именно по количеству children и отрисовывает для каждого страничку.
Соответственно, вместо этого блока, была просто пустая страница.
Решение нашёл у них в issues - возвращать false значение и фильтровать children.

2022-09-21 11:25 UTC, sarious approved these changes

2022-09-21 11:26 UTC, merged