ui_improvement: add Table skeleton loading. Add adaptive for new scre…
mapofzones/map-of-zones-web pull request #190
Opened 2022-09-23 11:27 UTC by ALashchotka

…ens. Fix some UI bugs

2022-09-23 13:33 UTC, sarious requested changes

2022-09-23 13:33 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +  const { data: zonesTotalInfo } = useAssetsTotalInfo();
добавь тут loading. useQuery возвращает loading

2022-09-23 13:33 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +      <TotalCard className={styles.card} loading={!zonesTotalInfo}>
тут тоже использовать loading из useAssetsTotalInfo

2022-09-23 13:33 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +      <TotalCard className={styles.card} loading={!zonesTotalInfo}>
пусть будет лоадинг когда идет загрузка, а когда нет данных пусть прочерки показываются

2022-09-23 13:33 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isMobile} />}
а почему тут показываешь только если есть allZonesCount ??

2022-09-23 13:33 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTotalInfo/ZonesTotalInfo.tsx
>    const { data: zonesTotalInfo } = useZonesTotalInfo(selectedPeriod);
то же самое. useQuery возвращает loading. прокидывай сюда и используй loading проперти

2022-09-23 13:33 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +            <>
а чего скрываешь All Assets если нет данных? это же просто статический текст

2022-09-23 14:27 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +            <>
Тут по дизайну всё 
https://www.figma.com/file/N7YvR1JGw6dqsTUiIPmCQO/MoZ---UX%2FUI?node-id=3282%3A17290

2022-09-23 14:28 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isMobile} />}
Так в дизайне:
https://www.figma.com/file/N7YvR1JGw6dqsTUiIPmCQO/MoZ---UX%2FUI?node-id=2718%3A10181

2022-09-23 16:55 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +  const { data: zonesTotalInfo } = useAssetsTotalInfo();
Done

2022-09-23 16:55 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +      <TotalCard className={styles.card} loading={!zonesTotalInfo}>
Done

2022-09-23 16:56 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTotalInfo/ZonesTotalInfo.tsx
>    const { data: zonesTotalInfo } = useZonesTotalInfo(selectedPeriod);
Done

2022-09-23 16:59 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTable/AssetsTable.tsx
> +      {!!sortedData.length && <div className={styles.header}>All Tokens</div>}
Done

2022-09-23 19:58 UTC, sarious commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isMobile} />}
хм, так зависит же не от allZonesCount

2022-09-24 08:07 UTC, sarious commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +            <>
сказали, что можно и показывать статичные данные

2022-09-24 11:31 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isMobile} />}
По сути да, но я показываю вместе с хедером и переключатель. Возможно, его вообще не стоит прятать

2022-09-24 11:37 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isMobile} />}
сделал, чтобы показывалось всегда

2022-09-24 11:38 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +            <>
Показываю всегда

2022-09-24 12:17 UTC, sarious requested changes

2022-09-24 12:20 UTC, sarious requested changes

2022-09-24 12:20 UTC, sarious commented on src/pages/AssetsPage/AssetsTable/AssetsTable.tsx
> +      {!sortedData.length && <TableSkeleton />}
тут по лоадингу скрывать показывать

2022-09-24 12:26 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTable/AssetsTable.tsx
> +      </SkeletonTextWrapper>
Done

2022-09-24 12:27 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTotalInfo/AssetsTotalInfo.tsx
> +            {/* <div className={styles.additionalValue}>{zonesTotalInfo.topMarketTokenSymbol}</div> */}
Done

2022-09-24 12:27 UTC, ALashchotka commented on src/pages/AssetsPage/AssetsTable/AssetsTable.tsx
> +      {!sortedData.length && <TableSkeleton />}
Done

2022-09-24 12:27 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +        {!!zonesCountData?.allZonesCount && <PeriodSelector useDropdown={isTabletSmall} />}
Done

2022-09-24 12:27 UTC, ALashchotka commented on src/pages/ZonesPage/ZonesInfo/ZonesTable/ZonesTable.tsx
> +      {!sortedZones.length && <TableSkeleton />}
Done

2022-09-24 12:33 UTC, sarious approved these changes

2022-09-24 12:34 UTC, merged